// vue/src/FormulaInput.vue
<template>
  <div class="fm-colored-input">
    <div
      :class="{
        'fm-colored-input__wrapper--focused': isFocused
      }"
      class="fm-colored-input__wrapper"
    >
      <textarea
        ref="textareaRef"
        v-model="modelValue"
        class="fm-colored-input__textarea"
        autocomplete="off"
        autocorrect="off"
        autocapitalize="off"
        spellcheck="false"
        rows="1"
        @focus="isFocused = true"
        @blur="isFocused = false"
      />
      <div class="fm-colored-input__highlight">
        <span
          v-for="(highlightEntry, highlightEntryIndex) in highlight"
          :key="highlightEntry.value + highlightEntryIndex"
          :class="highlightEntry.css"
        >
          {{ highlightEntry.value }}
        </span>
      </div>
    </div>
    <div class="fm-colored-input__validation">
      {{ props.validationErrors?.map(error => error.errorType).join(', ') }}
    </div>
  </div>
</template>

<script setup lang="ts">
import { defineProps, defineEmits, ref, computed, watch, onBeforeUnmount } from 'vue'
import type { Token, ValidationError } from '../../shared/src'

type Props = {
  modelValue: string,
  tokens?: Token[],
  validationErrors?: ValidationError[]
}

const props = defineProps<Props>()
const emit = defineEmits(['update:model-value'])
const isFocused = ref(false)
const modelValue = ref('')
const textareaRef = ref<HTMLTextAreaElement>()

const updateHeight = () => {
  const el = textareaRef.value
  if (el) {
    el.style.height = 'auto'
    el.style.height = el.scrollHeight + 'px'
    setTimeout(() => {
      el.style.height = 'auto'
      el.style.height = el.scrollHeight + 'px'
    }, 0)
  }
}

const highlight = computed(() => {
  const errorsByTokenIndexes = props.validationErrors?.reduce((out: Record<number, boolean>, error) => {
    if (error.tokenIndex || error.tokenIndex === 0) {
      out[error.tokenIndex] = true
    }
    return out
  }, {})
  return props.tokens?.map((token, tokenIndex) => ({
    value: token.value,
    css: `fm-colored-input__highlight--${token.type}` + (errorsByTokenIndexes?.[tokenIndex] ? ' fm-colored-input__highlight--error' : '')
  }))
})

watch(() => props.modelValue, (value) => {
  modelValue.value = value
}, { immediate: true })

watch(modelValue, (value) => {
  emit('update:model-value', value)
  updateHeight()
}, { immediate: true })

const resizeObserver = new ResizeObserver(() => {
  updateHeight()
})

watch(textareaRef, (value) => {
  value && resizeObserver.observe(value)
})

onBeforeUnmount(() => {
  resizeObserver.disconnect()
})

</script>

// react/src/FormulaInput.tsx
import { useState, useMemo, useRef, useLayoutEffect } from 'react'
import type { Token, ValidationError } from './shared/src'

type Props = {
  modelValue: string
  onChange: (value: string) => void
  tokens?: Token[]
  validationErrors?: ValidationError[]
}

export function FormulaInput(props: Props) {
  const { modelValue, onChange, tokens, validationErrors } = props
  const [isFocused, setFocused] = useState(false)

  const highlight = useMemo(() => {
    const errorsByTokenIndexes = validationErrors?.reduce((out: Record<number, boolean>, error) => {
      if (error.tokenIndex || error.tokenIndex === 0) {
        out[error.tokenIndex] = true
      }
      return out
    }, {})
    return tokens?.map((token, tokenIndex) => ({
      value: token.value,
      css: `fm-colored-input__highlight--${token.type}` + (errorsByTokenIndexes?.[tokenIndex] ? ' fm-colored-input__highlight--error' : '')
    }))
  }, [tokens, validationErrors])

  const textareaRef = useRef(null)

  const updateHeight = (el?: HTMLTextAreaElement | null) => {
    if (el) {
      el.style.height = 'auto'
      el.style.height = el.scrollHeight + 'px'
      setTimeout(() => {
        el.style.height = 'auto'
        el.style.height = el.scrollHeight + 'px'
      }, 0)
    }
  }

  useLayoutEffect(() => {
    updateHeight(textareaRef.current)
  }, [modelValue])  

  useLayoutEffect(() => {
    const resizeObserver = new ResizeObserver(() => {
      updateHeight(textareaRef.current)
    })
    if (textareaRef.current) {
      resizeObserver.observe(textareaRef.current)
    }
    return () => {
      resizeObserver.disconnect()
    }
  }, [textareaRef])

  return (
    <div className="fm-colored-input">
      <div className={'fm-colored-input__wrapper' + (isFocused ? ' fm-colored-input__wrapper--focused' : '')}>
        <textarea
          ref={textareaRef}
          value={modelValue}
          className="fm-colored-input__textarea"
          autoComplete="off"
          autoCorrect="off"
          autoCapitalize="off"
          spellCheck="false"
          rows={1}
          onFocus={() => setFocused(true)}
          onBlur={() => setFocused(false)}
          onChange={event => onChange(event.target.value)}
        />
        <div className="fm-colored-input__highlight">
          {highlight?.map((highlightEntry, highlightEntryIndex) => (
            <span
              key={highlightEntry.value + highlightEntryIndex}
              className={highlightEntry.css}
            >
              {highlightEntry.value}
            </span>
          ))}
        </div>
      </div>
      <div className="fm-colored-input__validation">
        {validationErrors?.map(error => error.errorType).join(', ') }
      </div>
    </div>
  )
}
